apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: test-app
spec:
  containers:
  - name: nginx-app
    image: nginx
    ports: 
      - containerPort: 80
  - name: mysql-app
    image: mariadb:latest
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: my-cred
            key: USER_N
            